services:
  flask:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: flask_app
    restart: always
    env_file:
      - rc-DACFOI.env
    expose:
      - "8000:8000"
#    volumes:
#      - ./backend:/app/backend
#      - ./frontend:/app/frontend
#      - ./instance:/app/instance

  nginx:
    build:
      context: .
      dockerfile: docker/Dockerfile.nginx
    container_name: nginx_server
    restart: always
    ports:
      - "80:80"
    depends_on:
      - flask
    volumes:
      - ./frontend:/frontend