"""Initial migration

Revision ID: 3e3d558f5eb2
Revises: 
Create Date: 2025-02-17 01:43:51.146613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e3d558f5eb2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faculty',
    sa.Column('faculty_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('school', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=False),
    sa.Column('about', sa.Text(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('profile_url', sa.String(), nullable=True),
    sa.Column('has_funding', sa.Boolean(), nullable=True),
    sa.Column('embedding_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('faculty_id')
    )
    op.create_table('projects',
    sa.Column('project_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.Column('project_number', sa.String(), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('relevant_terms', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('agency_ic_admin', sa.String(), nullable=True),
    sa.Column('activity_code', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty.faculty_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projects')
    op.drop_table('faculty')
    # ### end Alembic commands ###
