"""empty message

Revision ID: 8a4a36261782
Revises: 3e3d558f5eb2
Create Date: 2025-08-07 23:05:01.468966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a4a36261782'
down_revision = '3e3d558f5eb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grants',
    sa.Column('grant_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nsf_id', sa.String(), nullable=False),
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty.faculty_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('grant_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grants')
    # ### end Alembic commands ###
