"""Updated models: added Department table and Faculty-Department many-to-many relationship

Revision ID: eb0eb92ccbaf
Revises: 
Create Date: 2025-02-13 16:00:14.744461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb0eb92ccbaf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('faculty')
    op.drop_table('projects')

    op.create_table(
        'faculty',
        sa.Column('faculty_id', sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('school', sa.String(), nullable=False),
        sa.Column('about', sa.Text(), nullable=True),
        sa.Column('email', sa.String(), nullable=True),
        sa.Column('profile_url', sa.String(), nullable=True),
        sa.Column('embedding_id', sa.Integer(), nullable=False),
    )

    # Recreate projects table
    op.create_table(
        'projects',
        sa.Column('project_id', sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column('faculty_id', sa.Integer(), sa.ForeignKey('faculty.faculty_id', ondelete='CASCADE'), nullable=False),
        sa.Column('project_number', sa.String(), nullable=False),
        sa.Column('abstract', sa.Text(), nullable=True),
        sa.Column('relevant_terms', sa.Text(), nullable=True),
        sa.Column('start_date', sa.Date(), nullable=True),
        sa.Column('end_date', sa.Date(), nullable=True),
        sa.Column('agency_ic_admin', sa.String(), nullable=True),
        sa.Column('activity_code', sa.String(), nullable=True),
    )

    # Create department table (if not already created)
    op.create_table(
        'department',
        sa.Column('department_id', sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column('name', sa.String(), nullable=False, unique=True),
    )

    # Create faculty_department association table for many-to-many relationship
    op.create_table(
        'faculty_department',
        sa.Column('faculty_id', sa.Integer(), sa.ForeignKey('faculty.faculty_id'), primary_key=True),
        sa.Column('department_id', sa.Integer(), sa.ForeignKey('department.department_id'), primary_key=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('faculty_department')
    op.drop_table('projects')
    op.drop_table('faculty')
    op.drop_table('department')

    op.create_table('projects',
    sa.Column('project_id', sa.INTEGER(), nullable=False),
    sa.Column('faculty_id', sa.INTEGER(), nullable=False),
    sa.Column('project_number', sa.VARCHAR(), nullable=False),
    sa.Column('abstract', sa.TEXT(), nullable=True),
    sa.Column('relevant_terms', sa.TEXT(), nullable=True),
    sa.Column('start_date', sa.DATE(), nullable=True),
    sa.Column('end_date', sa.DATE(), nullable=True),
    sa.Column('agency_ic_admin', sa.VARCHAR(), nullable=True),
    sa.Column('activity_code', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty.faculty_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('faculty',
    sa.Column('faculty_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('school', sa.VARCHAR(), nullable=False),
    sa.Column('department', sa.VARCHAR(), nullable=False),
    sa.Column('about', sa.TEXT(), nullable=True),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('profile_url', sa.VARCHAR(), nullable=True),
    sa.Column('embedding_id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('faculty_id')
    )
    # ### end Alembic commands ###
